kinematic_tree_metadata:
  body_names:
    feet:
      r: &R_FOOT_NAME "rightFoot"
      l: &L_FOOT_NAME "leftFoot"
    pelvis: &PELVIS_NAME pelvis
    hands:
      r: &R_HAND_NAME rightPalm
      l: &L_HAND_NAME leftPalm

  joint_group_names:
    legs:
      r: [rightHipYaw, rightHipRoll, rightHipPitch, rightKneePitch, rightAnklePitch, rightAnkleRoll]
      l: [leftHipYaw, leftHipRoll, leftHipPitch, leftKneePitch, leftAnklePitch, leftAnkleRoll]
    knees:
      r: rightKneePitch
      l: leftKneePitch
    ankles:
      r: [rightAnklePitch, leftAnkleRoll]
      l: [leftAnklePitch, rightAnkleRoll]
    arms:
      r: [rightShoulderPitch, rightShoulderRoll, rightShoulderYaw, rightElbowPitch, rightForearmYaw, rightWristRoll, rightWristPitch]
      l: [leftShoulderPitch, leftShoulderRoll, leftShoulderYaw, leftElbowPitch, leftForearmYaw, leftWristRoll, leftWristPitch]

    neck: [lowerNeckPitch]
    back_bkz: torsoYaw
    back_bky: torsoPitch

joint_names:
  - torsoYaw
  - torsoPitch
  - torsoRoll
  - lowerNeckPitch
  - neckYaw
  - upperNeckPitch
  - rightShoulderPitch
  - rightShoulderRoll
  - rightShoulderYaw
  - rightElbowPitch
  - rightForearmYaw
  - rightWristRoll
  - rightWristPitch
  - leftShoulderPitch
  - leftShoulderRoll
  - leftShoulderYaw
  - leftElbowPitch
  - leftForearmYaw
  - leftWristRoll
  - leftWristPitch
  - rightHipYaw
  - rightHipRoll
  - rightHipPitch
  - rightKneePitch
  - rightAnklePitch
  - rightAnkleRoll
  - leftHipYaw
  - leftHipRoll
  - leftHipPitch
  - leftKneePitch
  - leftAnklePitch
  - leftAnkleRoll

actuator_names:
  - torsoYaw
  - waistPitchActuator
  - waistRollActuator
  - lowerNeckPitch
  - neckYaw
  - upperNeckPitch
  - rightShoulderPitch
  - rightShoulderRoll
  - rightShoulderYaw
  - rightElbowPitch
  - rightForearmYaw
  - rightWristRoll
  - rightWristPitch
  - leftShoulderPitch
  - leftShoulderRoll
  - leftShoulderYaw
  - leftElbowPitch
  - leftForearmYaw
  - leftWristRoll
  - leftWristPitch
  - rightHipYaw
  - rightHipRoll
  - rightHipPitch
  - rightKneePitch
  - rightAnklePitchActuator
  - rightAnkleRollActuator
  - leftHipYaw
  - leftHipRoll
  - leftHipPitch
  - leftKneePitch
  - leftAnklePitchActuator
  - leftAnkleRollActuator



qp_controller_params:
  DEFAULT:
    body_specific:
      DEFAULT:
        Kp: {x: 12, y: 12, z: 12, wx: 12, wy: 12, wz: 12}
        damping_ratio: 0.7
        accel_bounds:
          min: {x: -100, y: -100, z: -100, wx: -50, wy: -50, wz: -50}
          max: {x: 100, y: 100, z: 100, wx: 50, wy: 50, wz: 50}
        weight: 0.0
      *PELVIS_NAME :
        Kp: {x: 15, y: 15, z: 15, wx: 40, wy: 40, wz: 40}
        weight: 1
        damping_ratio: 0.3
      *R_FOOT_NAME :
        Kp: {x: 40, y: 40, z: 40, wx: 60, wy: 60, wz: 40}
        weight: 0.1
      *L_FOOT_NAME :
        Kp: {x: 40, y: 40, z: 40, wx: 60, wy: 60, wz: 40}
        weight: 0.1
    position_specific:
      DEFAULT:
        Kp: 150
        damping_ratio: 0.2
        w_qdd: 0.001
        integrator:
          gain: 1.75
          clamp: 0.1
        qdd_bounds:
          min: -100
          max: 100
        joint_soft_limits:
          enabled: false
          lb: -.inf
          ub: .inf
          kp: 150
          damping_ratio: 0.6
          weight: 1e-5
          disable_when_body_in_support: ""
          k_logistic: 20
      base_x:
        w_qdd: 0
      base_y:
        w_qdd: 0
      base_z:
        w_qdd: 0
      base_roll:
        w_qdd: 0
      base_pitch:
        w_qdd: 0
      base_yaw:
        w_qdd: 0
      torsoRoll:
        w_qdd: 0.1
        Kp: 50
        damping_ratio: 0.2
      torsoPitch:
        w_qdd: 0.1
        Kp: 50
        damping_ratio: 0.2
      rightKneePitch:
        joint_soft_limits:
          enabled: true
          lb: 0.5
          disable_when_body_in_support: *R_FOOT_NAME
      leftKneePitch:
        joint_soft_limits:
          enabled: true
          lb: 0.5
          disable_when_body_in_support: *L_FOOT_NAME
    vref_integrator:
      zero_ankles_on_contact: false
      eta: 0.001
      delta_max: 10
    integrator:
      eta: 0.0
    W_kdot: 0
    Kp_ang: 0
    w_slack: 20.0
    Jpdotv_multiplier: 0.0
    slack_limit: 20
    w_grf: 0.00
    mu: 1
    w_zmp: 100.0
    w_qdd_delta: 0.0
    Kp_accel: 1.0
    contact_threshold: 0.002
    useTorqueAlphaFilter: True
    min_knee_angle: 0.7
    center_of_mass_observer:
      enabled: false
      l_zmp: 10
      l_com: 6.324555320336759 # 2 * sqrt(l_zmp)
    input_specific:
      DEFAULT:
        hardware:
          joint_is_force_controlled: true
          joint_is_position_controlled: false
          k_f_p: 0
          k_q_p: 0
          k_q_i: 0
          k_qd_p: 0
          ff_qd: 0
          ff_f_d: 1
          ff_const: 0
          ff_qd_d: 1.0
      upperNeckPitch:
        hardware:
          joint_is_force_controlled: false
          joint_is_position_controlled: true
      lowerNeckPitch:
        hardware:
          joint_is_force_controlled: false
          joint_is_position_controlled: true
      neckYaw:
        hardware:
          joint_is_force_controlled: false
          joint_is_position_controlled: true

      waistPitchActuator:
        hardware:
          ff_qd_d: 2.0

      waistRollActuator:
        hardware:
          ff_qd_d: 2.0

      leftHipYaw:
        hardware:
          ff_qd_d: 2.0

      leftHipRoll:
        hardware:
          ff_qd_d: 2.0

      leftHipPitch:
        hardware:
          ff_qd_d: 5.0

      leftKneePitch:
        hardware:
          ff_qd_d: 10.0

      leftAnklePitchActuator:
        hardware:
          ff_qd_d: 2.0

      leftAnkleRollActuator:
        hardware:
          ff_qd_d: 2.0

      rightHipYaw:
        hardware:
          ff_qd_d: 2.0

      rightHipRoll:
        hardware:
          ff_qd_d: 2.0

      rightHipPitch:
        hardware:
          ff_qd_d: 5.0

      rightKneePitch:
        hardware:
          ff_qd_d: 10.0

      rightAnklePitchActuator:
        hardware:
          ff_qd_d: 2.0

      rightAnkleRollActuator:
        hardware:
          ff_qd_d: 2.0

  base: # automatically inherits from the default =
  standing:
  manip:
  walking:
    #    body_specific:
    #  *PELVIS_NAME :
    #    Kp: {x: 0, y: 0, z: 15, wx: 40, wy: 40, wz: 40}
    #   weight: 10.0
    #    damping_ratio: 0.3
    #  *R_FOOT_NAME :
    #    Kp: {x: 30, y: 30, z: 30, wx: 30, wy: 30, wz: 30}
    #    weight: 10.0
    #    damping_ratio: 0.4
    #  *L_FOOT_NAME :
    #    Kp: {x: 30, y: 30, z: 30, wx: 30, wy: 30, wz: 30}
    #    weight: 10.0
    #    damping_ratio: 0.4
