kinematic_tree_metadata:
  body_names:
    feet:
      r: &R_FOOT_NAME rightFoot
      l: &L_FOOT_NAME leftFoot
    pelvis: &PELVIS_NAME pelvis
    hands:
      r: &R_HAND_NAME rightPalm
      l: &L_HAND_NAME leftPalm
    torso: &TORSO_NAME torso

  joint_group_names:
    legs:
      r: [rightHipYaw, rightHipRoll, rightHipPitch, rightKneePitch, rightAnklePitch, rightAnkleRoll]
      l: [leftHipYaw, leftHipRoll, leftHipPitch, leftKneePitch, leftAnklePitch, leftAnkleRoll]
    knees:
      r: rightKneePitch
      l: leftKneePitch
    ankles:
      r: [rightAnklePitch, leftAnkleRoll]
      l: [leftAnklePitch, rightAnkleRoll]
    arms:
      r: [rightShoulderPitch, rightShoulderRoll, rightShoulderYaw, rightElbowPitch, rightForearmYaw, rightWristRoll, rightWristPitch]
      l: [leftShoulderPitch, leftShoulderRoll, leftShoulderYaw, leftElbowPitch, leftForearmYaw, leftWristRoll, leftWristPitch]

    neck: [lowerNeckPitch]
    back_bkz: torsoYaw
    back_bky: torsoPitch

foot_contact_offsets:
  *L_FOOT_NAME :
    left_toe: {x: 0.172, y: 0.055, z: -0.09}
    right_toe: {x: 0.172, y: -0.055, z: -0.09}
    left_heel: {x: -0.058, y: 0.055, z: -0.09}
    right_heel: {x: -0.058, y: -0.055, z: -0.09}
  *R_FOOT_NAME :
    left_toe: {x: 0.172, y: 0.055, z: -0.09}
    right_toe: {x: 0.172, y: -0.055, z: -0.09}
    left_heel: {x: -0.058, y: 0.055, z: -0.09}
    right_heel: {x: -0.058, y: -0.055, z: -0.09}

# shared by manip and walking
mu: 1
zmp_height: 0.95
initial_transition_time: 0.2
transition_trq_alpha_filter: 0.9
flip_foot_ft_sensor: 1

# walking
ss_duration: 1.
ds_duration: 0.5
pre_weight_transfer_scale: 0.3
min_Fz: 5
lower_z_vel: -0.3
swing_foot_xy_weight_mulitplier: 15.0
pelvis_z_weight_mulitplier: 5.0
left_foot_zmp_y_shift: -0.01
right_foot_zmp_y_shift: 0.0
