kinematic_tree_metadata:
  body_names:
    feet:
      r: &R_FOOT_NAME rightFoot
      l: &L_FOOT_NAME leftFoot
    pelvis: &PELVIS_NAME pelvis
    hands:
      r: &R_HAND_NAME rightPalm
      l: &L_HAND_NAME leftPalm
    torso: &TORSO_NAME torso

  joint_group_names:
    legs:
      r: [rightHipYaw, rightHipRoll, rightHipPitch, rightKneePitch, rightAnklePitch, rightAnkleRoll]
      l: [leftHipYaw, leftHipRoll, leftHipPitch, leftKneePitch, leftAnklePitch, leftAnkleRoll]
    knees:
      r: rightKneePitch
      l: leftKneePitch
    ankles:
      r: [rightAnklePitch, leftAnkleRoll]
      l: [leftAnklePitch, rightAnkleRoll]
    arms:
      r: [rightShoulderPitch, rightShoulderRoll, rightShoulderYaw, rightElbowPitch, rightForearmYaw, rightWristRoll, rightWristPitch]
      l: [leftShoulderPitch, leftShoulderRoll, leftShoulderYaw, leftElbowPitch, leftForearmYaw, leftWristRoll, leftWristPitch]

    neck: [lowerNeckPitch]
    back_bkz: torsoYaw
    back_bky: torsoPitch
    back_bkx: torsoRoll

foot_contact_offsets:
  *L_FOOT_NAME :
    left_toe: {x: 0.15, y: 0.055, z: -0.09}
    right_toe: {x: 0.15, y: -0.055, z: -0.09}
    left_heel: {x: -0.05, y: 0.055, z: -0.09}
    right_heel: {x: -0.05, y: -0.055, z: -0.09}
  *R_FOOT_NAME :
    left_toe: {x: 0.15, y: 0.055, z: -0.09}
    right_toe: {x: 0.15, y: -0.055, z: -0.09}
    left_heel: {x: -0.05, y: 0.055, z: -0.09}
    right_heel: {x: -0.05, y: -0.055, z: -0.09}

# shared by manip and walking
mu: 1
zmp_height: 0.97 # measured from the soles of feet
initial_transition_time: 0.2
transition_trq_alpha_filter: 0.9
flip_foot_ft_sensor: 1

# walking
pelvis_height: 0.97 # measured from the ankles
ss_duration: 1
ds_duration: 0.5
min_Fz: 5
use_force_bounds: True
extend_foot_down_z_vel: -0.06
swing_touchdown_z_vel: -0.06
swing_touchdown_z_offset: -0.03

constrainBackJoints:
  back_bkx: false
  back_bky: false
  back_bkz: false

swing_foot_xy_weight_mulitplier: 15.0
swing_foot_z_weight_mulitplier: 15.0
pelvis_z_weight_mulitplier: 5.0
left_foot_zmp_y_shift: 0.0
right_foot_zmp_y_shift: 0.01
