kinematic_tree_metadata:
  body_names:
    feet:
      r: &R_FOOT_NAME r_foot
      l: &L_FOOT_NAME l_foot
    pelvis: &PELVIS_NAME pelvis
    hands:
      r: &R_HAND_NAME r_hand
      l: &L_HAND_NAME l_hand
    torso: &TORSO_NAME utorso

  joint_group_names:
    legs:
      r: [r_leg_hpz, r_leg_hpx, r_leg_hpy, r_leg_kny, r_leg_aky, r_leg_akx]
      l: [l_leg_hpz, l_leg_hpx, l_leg_hpy, l_leg_kny, l_leg_aky, l_leg_akx]
    knees:
      r: r_leg_kny
      l: l_leg_kny
    ankles:
      r: [r_leg_aky, r_leg_akx]
      l: [l_leg_aky, l_leg_akx]
    arms:
      r: [r_arm_shz, r_arm_shx, r_arm_ely, r_arm_elx, r_arm_uwy, r_arm_mwx, r_arm_lwy]
      l: [l_arm_shz, l_arm_shx, l_arm_ely, l_arm_elx, l_arm_uwy, l_arm_mwx, l_arm_lwy]
    neck: [neck_ay]
    back_bkz: back_bkz
    back_bky: back_bky
    back_bkx: back_bkx

foot_contact_offsets:
  *L_FOOT_NAME :
    left_toe: {x: 0.1728, y: 0.0626, z: -0.07645}
    right_toe: {x: 0.1728, y: -0.0626, z: -0.07645}
    left_heel: {x: -0.0876, y: 0.0626, z: -0.07645}
    right_heel: {x: -0.0876, y: -0.0626, z: -0.07645}
  *R_FOOT_NAME :
    left_toe: {x: 0.1728, y: 0.0626, z: -0.07645}
    right_toe: {x: 0.1728, y: -0.0626, z: -0.07645}
    left_heel: {x: -0.0876, y: 0.0626, z: -0.07645}
    right_heel: {x: -0.0876, y: -0.0626, z: -0.07645}

# shared by manip and walking
mu: 0.7
zmp_height: 1.0 # note we may need to turn this down
initial_transition_time: 0.2
transition_trq_alpha_filter: 0.0
flip_foot_ft_sensor: 0

# walking
pelvis_height: 0.75 # measured as height from ankles
ss_duration: 1.0
ds_duration: 0.5
pre_weight_transfer_scale: 0.3 # what does this actually do?
min_Fz: 50
extend_foot_down_z_vel: -0.05
swing_touchdown_z_vel: 0.0
swing_touchdown_z_offset: 0.0

swing_foot_xy_weight_mulitplier: 1.0
swing_foot_z_weight_mulitplier: 1.0
pelvis_z_weight_mulitplier: 1.0
left_foot_zmp_y_shift: 0.0
right_foot_zmp_y_shift: -0.0

# note this interacts with the torso orientation tracking constraint
# so be careful
constrainBackJoints:
  back_bkx: false
  back_bky: true
  back_bkz: true



# FOR DEBUGGING PURPOSES
# this is currently just copied over from Atlas.m where default walking params are
nominal_LIP_COM_height: 0.8 # nominal height used to construct D_ls for our linear inverted pendulum model, this is D_control

# the actual com height during walking, i.e. com height given that
# the pelvis is at 0.83 is something like 1.08

# I think that c_plan_eval uses the real COM height

# copied from Atlas.m
pelvis_height_above_foot_sole: 0.83 # this is D_control

