kinematic_tree_metadata:
  body_names:
    feet:
      r: &R_FOOT_NAME r_foot
      l: &L_FOOT_NAME l_foot
    pelvis: &PELVIS_NAME pelvis
    hands:
      r: &R_HAND_NAME r_hand
      l: &L_HAND_NAME l_hand
    torso: &TORSO_NAME utorso

  joint_group_names:
    legs:
      r: [r_leg_hpz, r_leg_hpx, r_leg_hpy, r_leg_kny, r_leg_aky, r_leg_akx]
      l: [l_leg_hpz, l_leg_hpx, l_leg_hpy, l_leg_kny, l_leg_aky, l_leg_akx]
    knees:
      r: r_leg_kny
      l: l_leg_kny
    ankles:
      r: [r_leg_aky, r_leg_akx]
      l: [l_leg_aky, l_leg_akx]
    arms:
      r: [r_arm_shz, r_arm_shx, r_arm_ely, r_arm_elx, r_arm_uwy, r_arm_mwx, r_arm_lwy]
      l: [l_arm_shz, l_arm_shx, l_arm_ely, l_arm_elx, l_arm_uwy, l_arm_mwx, l_arm_lwy]
    neck: [neck_ay]
    back_bkz: back_bkz
    back_bky: back_bky

foot_contact_offsets:
  *L_FOOT_NAME :
    left_toe: {x: 0.1728, y: 0.0626, z: -0.07645}
    right_toe: {x: 0.1728, y: -0.0626, z: -0.07645}
    left_heel: {x: -0.0876, y: 0.0626, z: -0.07645}
    right_heel: {x: -0.0876, y: -0.0626, z: -0.07645}
  *R_FOOT_NAME :
    left_toe: {x: 0.1728, y: 0.0626, z: -0.07645}
    right_toe: {x: 0.1728, y: -0.0626, z: -0.07645}
    left_heel: {x: -0.0876, y: 0.0626, z: -0.07645}
    right_heel: {x: -0.0876, y: -0.0626, z: -0.07645}

mu: 0.7
zmp_height: 0.8
initial_transition_time: 0.5
transition_trq_alpha_filter: 0.9
flip_foot_ft_sensor: 0

ss_duration: 2.0
ds_duration: 2.0
pre_weight_transfer_scale: 0.3
min_Fz: 100
lower_z_vel: -0.1

